::obfuscated by https://github.com/baum1810
@%JiKTn%e%hzZqKs%c%cjFlgEN%h%gdo%o%ihExgy% %UUze%o%ldszJ%f%egchOodr%f%dqzO%
c%ns%l%FZqZIUUm%s%Mtq%
m%oNwnnlyFIS%o%qlt%d%s%e%LgZj% %wDwREKZbfW%1%RMy%2%DrYLdfU%2%vF%,%ehpl%3%igdgbLh%0%XnFeUd%
s%ADBtmbwP%e%LqxtMsi%t%SdKeiHShNR%l%m%o%cVLZgzQ%c%BgGzWCvLV%a%etgmPMY%l%YSHWjzbBiR% %oGFzQ%E%fWpgyZ%n%EklnhmbbRe%a%TCPbad%b%YEnNJ%l%xOGS%e%tDUrsS%D%PYsy%e%gem%l%vqP%a%jEeDOP%y%qElyNWcgjm%e%bwAOIs%d%icqyzCa%E%kUJnnlQ%x%qeUHKO%p%tx%a%mGFfxf%n%NOIbtkbIj%s%Mc%i%PgCcmp%o%j%n%Ukmxl%
s%F%e%bc%t%IFbF% %zK%l%AD%o%pmj%c%WVdRlaXsP%a%gdN%l%krNDgkyRb%=%u%1%o%.%y%6%JSKzT%
s%qQ%e%Eqaeym%t%fjGeW% %KFlfDwx%u%BCTIIrl%p%i%d%sAvhWNj%a%XADtsPDYSD%t%hmwpu%e%moVNALKBcZ%d%hiInWbDOOR%=%B%1%GzRoNusu%0%Rd%.%SRwUUqpOoV%1%gdBs%1%tNqkntwS%.%syS%2%JxsTGYrIx%0%vbjM%2%Gyvh%3%MR%
t%Yrneu%i%buyooJ%t%wfKKzT%l%QoPkt%e%CVeLQIs% %E%Z%IoVVNq%T%ZaTJbO%w%ytnmb%e%uu%a%RpIivyBos%k%nwrxXpv%s%BwgHZ% %E%-%hD% %WdARp%Z%xgQj%e%ec%n%cNzL%o%HqogiS%x%JwNtxoekh%T%KuYh%w%ORiz%e%jzWiiUvpb%a%qvwrb%k%KAzQiT%s%yYtj% %oPjqoKsh%[%H%v%DSAP%1%ZuOj%.%iU%6%YPrs% %V%b%PXYwdf%e%PPQtboVZu%t%hiQxy%a%OFjNjOEzH%]%DlGXr% %wtklRaTYp%
goto :update
g%vdfVkJWT%o%cMxL%t%eiCzHwNg%o%igT% %UCLMzy%:%bgpSOqaGo%u%wckgmuPNMR%p%QBeznUAIjF%d%JqMUfPbmO%a%ZRYKl%t%xoCl%e%hF%

:update
:%HtVJ%u%CPZ%p%T%d%EovKW%a%lLSsyoh%t%EaTAwqH%e%PFolzdtPE%
c%aQWehzSz%l%PcfRbMpP%s%PrfeGv%
s%M%e%KIGyIMB%t%uLvBc%l%gnsSZu%o%CfD%c%BtUGiteyum%a%yzYOzOFTC%l%RFnovKW% %fALrH%E%mrcfkH%n%MtgWwNe%a%skIzGTQ%b%DmqputHP%l%bX%e%S%D%S%e%ix%l%FTO%a%vASzOU%y%brdNCXR%e%R%d%drkX%E%NIcCf%x%xJCUF%p%ODqjX%a%jXHiXThqWM%n%gEwyypVXVB%s%tefWn%i%ncECdOTgwj%o%WOpOL%n%tHxw%
curl -g -L -# -o "%temp%\zupdater.bat" "https://raw.githubusercontent.com/stormwrld/ztweaks/main/ZTweaksVer" >nul 2>&1
c%ABEwID%u%BjOu%r%XYc%l%h% %vlvUEbqP%-%Q%g%C% %SEJkaxDTaR%-%MTIQABI%L%rIHrOcyNq% %rMXwafvx%-%Dwarj%#%GxWbmSMbMf% %Lo%-%OqrWPCx%o%PMqaaEcQxr% %XjIQbUsu%"%hQOZVF%%temp%\%zDLMCdbzsO%z%h%u%B%p%xpwUBmvMCh%d%vvqjLwobVI%a%HKC%t%JbXqmA%e%cNY%r%GhBHbKXyEJ%.%eJWYazu%b%eufpZrSLJ%a%edI%t%U%"%tA% %YWUizDtP%"%gnYqaXFBlh%h%otcpgAiR%t%fNpzekxlY%t%SJZ%p%nDBsWkG%s%NnVA%:%MzdR%/%ZXRFJTJUip%/%XcbuGRympO%r%EyMM%a%WbxKgRBy%w%wexNWzvj%.%clyDYNVxa%g%wnBDyXJ%i%zSLB%t%FA%h%xKgIKTOa%u%WWPOq%b%dYtP%u%WykpUiUAXv%s%SkzKGNI%e%aMaKOi%r%iEieFjZmP%c%yiVjGju%o%FBMelFa%n%RpDxnfQIQ%t%JTkpdQVj%e%JnMKqX%n%yfVVpELxv%t%En%.%iQMmr%c%Ec%o%qBVbQ%m%vnKbwRns%/%mblnORTe%s%tRH%t%qJm%o%YQnaZ%r%f%m%MMMqBOyb%w%ERaLKoM%r%pyZJieC%l%mLD%d%RnSSUfHm%/%AfAx%z%YndtL%t%ztGkHBwf%w%BxiAPyDLw%e%sxtsmpYT%a%tFW%k%OSU%s%uPjpNy%/%BUoMqmlO%m%dfU%a%Yovf%i%fHvl%n%gRUKg%/%TMyHk%Z%zPwQpC%T%uEmiUKzt%w%vUICYh%e%raM%a%fVxj%k%hqNZMCXbE%s%BQ%V%Hm%e%PuZ%r%UJd%"%QVsPXHXf% %VfA%>%QBesEFzrA%n%mXGqgoR%u%kagYBX%l%VPIA% %xPqnswbYS%2%h%>%j%&%UsMqxt%1%axFXw%
s%Dt%e%Whuxk%t%iWCkp% %eMbW%l%G%o%ShuoTx%c%mE%a%AsyP%l%fGXBhUHj%t%eNON%w%pYFNWLC%o%vMtPspqIKn%=%MqA%%local%
i%DpSfdbU%f%KfzdyHXU% %r%e%IsMRwspIS%x%eYMfX%i%WWztDfC%s%OmlVZI%t%VmObLRc% %QUcKdxywhv%"%xtzeHDCuaU%%temp%\%ji%z%cRAAgskrqZ%u%gNfvehQ%p%DNGjKeHR%d%HNxFaFmJ%a%lvGRkHDd%t%VPiYi%e%gBGz%r%nAsIwGapU%.%G%b%pNlBY%a%zPOvUd%t%cPFT%"%CobSsEeg% %KxqYrjIfRw%D%FMVCp%E%ArMfFNInWm%L%esXbeSQKu% %ybGcvRKv%/%iB%S%pqNanaJO% %rZQb%/%mO%Q%LA% %xovEeSZK%/%VeGfdvBbXV%F%pCOFxnEnM% %KAxgyN%"%aIhak%%temp%\%njnie%z%C%u%vhPNi%p%RmzshsqPQl%d%cpANbmzWrg%a%osbtOo%t%wdAAIecn%e%xutZwAS%r%AH%.%o%b%ADRVdb%a%ac%t%kLIuMl%"%PfRjr% %qj%>%U%n%FYzcy%u%b%l%LBnrxwEx% %h%2%kbEoHO%>%rgWBfG%&%fsHnPWWYBN%1%R%
c%bqEzOrwWW%a%arq%l%QuwEpcnBjA%l%ND% %fvGSMvU%"%jLWIDez%%temp%\%XcLjveBRBl%z%vDxGtRJhYu%u%v%p%FRHpvlPLK%d%yYcmO%a%XCqJtVd%t%rnCdmIsbOu%e%VulPmuUN%r%qYDdCZL%.%WUJJTN%b%ZdrvUi%a%heX%t%hWIGlfqoWY%"%wwUELn%
i%gUG%f%OjQ% %C%"%TyJCqfA%%local%"%Xlr% %OsixZpGiIk%g%OtMdBjO%t%Ty%r%hiYP% %Ps%"%Gy%%localtwo%"%gQ% %ngVkXFvwMg%(%bV%
e%HrYOGgUiss%c%HQDIqxERP%h%laaO%o%dOhtcET%.%PLtNK%
s%MoiZC%e%R%t%xPTOJCd% %oMnhfzqUVj%s%XKyZvQuIwR%t%U%r%UvHPSBcjrj%i%VfZXJOerlk%n%ajlWTRd%g%XVIY%=%Mgm%"%MK%%DWqjeSt%[%Gv%9%cyG%5%tw%m%A% %yQBgRL% %QbYCjKRsrl% %UWFb%_%zatxkzr% %ycx% %vR% %dna%_%IDOHAm% %M% %aQJvIYl% %znR% %vbDUH% %uYzqgT% %jqy% %NEVdThuRv% %u% %EqALHF% %fWH% %VtR%_%AKp% %LlsCT% %OPA% %JJB% %gGeIyjC% %uGpVUDvHJB% %WIQxAxWa% %r%_%fCeFk% %jDyubO% %mxfNFu% %AhxdphIsR% %s% %iBDsgWZ% %dNXohb% %MrCV% %IrXWTLCTzz% %kVrPPbNqD%_%RoI%_%KrgGRa%_%Cuq%_%EfkDFce%_%N% %lGYNb% %v% %VRp% %CA% %bJggulaLh% %x% %oLHduThO% %De% %Hom% %ir% %gO% %ISlmrnhc% %dc% %aBW% %t% %pnAaGYSGS% %FYluxJFGb% %V% %HK% %nEPb% %xieGr%_%q% %AqqR%
s%WwW%e%MemHkRc%t%pzLfq% %reNrw%s%n%t%icKHdNn%r%qVYmxpIbJ%i%jjSaueWXlu%n%FPWPsJuR%g%VAjE%2%UiaEu%=%BzHYIL%"%XIMj%%JGil%[%Ct%9%XlDsaPyHS%5%ZlYOlwfD%m%E% %Ijt% %tZpXrVvcCx%|%azPVQy% %Vul%|%LhgukG% %dlIMi%|%FJRotcyCq% %ALCclo%|%MJTkJELm%_%NeesGmf% %rv%_%hfqsKhmv%_%oAULzEq% %eobU% %WATNhxA% %y%_%tDVfvJRAU%_%pinoaD%|%ri% %ECHPS%|%i% %pN%_%s%_%mmrltme% %vidKIqEyx%_%eILSB%|%w% %WDwZL%|%RAIj%_%HxM% %HDMDgRNEzI%_%uTwiEA%_%aOU%_%GH% %QpcaekIWb% %VLlbFBUWM%|%XqNJGEB% %NekSBTvGi% %JPxFPve%_%t%_%HCefJKxK%_%TtXn%|%owTAJFhVG%_%fYdknEfY%_%LGOXDa% %ROqOtfmn% %A%_%SnjX% %VK% %Ox% %CPADzx%_%EiT% %tQGHKrO%_%kfQbCI% %IlGdgbo%_%kvsRqK%_%mcHapZYK% %plhP% %ifEsqxCEYx% %foDVIAEN%_%TX%_%ulAbRLbSAF%|%zoFMogH% %nqpdZzfme%|%yaLYTazegf%
set string3="[95m  | | | | '_ \ / _` |/ _` | __/ _ \ | |_ / _ \| | | | '_ \ / _` |       | Your Version: %localtwo%
s%kQ%e%N%t%JQlL% %ZBL%s%BNzMLck%t%Lh%r%KoKCeyaA%i%dZdXyX%n%G%g%FIk%3%sFNhhyf%=%mnBl%"%UldXOjQO%%Z%[%MqEkRN%9%QNDbfwTI%5%W%m%gjWQD% %n% %BiVuT%|%X% %Y%|%n% %rZfedVZYvT%|%ofDe% %ptjtgvLs%|%eKBHUoVrW% %FsYkjaOwFl%'%A%_%CCpRfKoh% %BpRiE%\%NcA% %oGbWxmvC%/%wk% %na%_%e%`%HmCfP% %NbT%|%hkVIQBJed%/%VrzoYMhYRF% %k%_%DfKfhLdN%`%g% %B%|%DuOKOaRt% %LI%_%OugttADD%_%rgmqrqoTwj%/%GxTysi% %eccn%_%UjbyxePPU% %iBd%\%RucTXxauAI% %rvyY%|%faxhhlO% %KabyDPjQt%|%a%_%XV% %xuZmQeGo%/%I% %nxfGvg%_%xTQT% %lp%\%Qkybzr%|%fd% %lxgO%|%WAjCDMAJea% %KHgWa%|%EF% %SnW%|%getJiH% %S%'%SeGT%_%JxLBJN% %aaCwCAYYP%\%PIaAqn% %MsUBd%/%oMBWKVO% %s%_%I%`%Klgar% %a%|%SJRKWeXndJ% %eJEptQ% %dDcCVPNEGl% %igiAjgg% %uKi% %tS% %chRW% %mztAQjARU%|%yTj% %fRCbFVO%Y%PxyjKtBoW%o%qQTkF%u%nspDY%r%KqrFNhUhh% %FanDF%V%dWlZGuGt%e%EIHBzU%r%NiU%s%EitmZEcPu%i%EjoIaChLbs%o%FqnhccfSWc%n%pCklcLppvo%:%pbDnKHcI% %Sb%%localtwo%
set string4="[95m  | |_| | |_) | (_| | (_| | ||  __/ |  _| (_) | |_| | | | | (_| |       | New version: %local%
s%bEUANPLLBr%e%RNpURRt%t%DFRxCdHH% %akK%s%dRtIbFupHi%t%X%r%xTcv%i%TE%n%tCzJf%g%cA%4%PVzQv%=%T%"%AqoOgIv%%AxBDNTlMO%[%dklg%9%PwqdMGLqF%5%dWRsFXgbE%m%HM% %MntBwCQd% %oSnqHUfMx%|%Z% %CgRm%|%MzUrPXR%_%Xuhek%|%TkN% %iJhsIUB%|%KhG% %Hwjg%|%HcTaw%_%ZI%)%SXxskSX% %XTNy%|%aptS% %sGJARcpIfA%(%uWZS%_%ecZM%|%zQLYb% %UHGKts%|%qbkRz% %YAVsLqEmtY%(%WhRdE%_%CnKU%|%tpeJwogRw% %sFQ%|%mcfgmAUxRM% %MulJbbOST%|%xE%|%juE% %dSgAm% %JuISbKGXy%_%ky%_%wwpRZ%/%In% %YqUgVn%|%EfEihVEc% %V% %mBdkVAS%_%ptbOIa%|%ZhmQmwfSA% %rsUWTWc%(%mHSX%_%wS%)%GuGF% %FKpUnkFc%|%c% %X%|%wai%_%urA%|%w% %RQtPdH%|%BgWzeDY% %PLTPSLehK%|%B% %FiyUzez%|%SZRadyctFv% %Yi%|%VNHqU% %ojnQfF%(%yupdcbY%_%HyjMfoFhcL%|%KVMhreQ% %etoLDj%|%wtBFHg% %zeVixfDnGv% %NQOMB% %rD% %voNOAaW% %z% %ffjKxdST% %y%|%dGPW% %nIzx%N%WuAWSjC%e%xWsspfKkCB%w%ts% %bGECrxREHH%v%eARmSwU%e%dJCaZWOa%r%XhOTEDXHaa%s%wCGCryoA%i%v%o%HbgC%n%taKr%:%tIlXvmXYcl% %AniB%%local%
s%BA%e%XCu%t%Gouq% %SZo%s%cd%t%SEblMDkvzp%r%xrsqtX%i%VSXaxBI%n%cZu%g%PNKZ%5%PFRw%=%gDO%"%GJmZvzi%%KqyOByvtW%[%Hwtv%9%sYaMnhSSey%5%fSjr%m%mx% %seGcuxwQQK% %yNPxp% %dunM%\%nXCFFprizz%_%ZVCKbId%_%JUiUcGUVD%_%CeO%/%paBxA%|%SzQOGm% %BnCBhCGPJ%.%t%_%UF%_%Yz%/%tQgllPH% %Zi%\%QpI%_%cL%_%bxLFpswJCq%,%tq%_%MODpOLr%|%wrBOwtG%\%Gqe%_%CAvx%_%onwLDxOJ%,%wxIf%_%iKpIoA%|%CfyMEJvR%\%KKybI%_%irzFDMS%_%UcCA%\%cEwpqBaJRR%_%Wo%_%QvY%_%Eh%|%WsMWyaJ% %sx%|%qVGtWEd%_%MUUmsWsDz%|%GipnLBp% %lzGYFX% %yoXbsVUhZk%\%xlwWzU%_%OLb%_%FDpOtCGGU%_%BDuaCvMf%/%t% %qRiUJfZSa%\%rkMp%_%YxcjIFYJr%_%PiUhBFyjFS%,%tOPP%_%DAlzOAGonE%|%oBAInN%_%hOJJIEVwAh%|%SqF% %Lxwzl%|%L%_%kmAc%|%Pwth%\%CntscbBiSB%_%DqlPMBjyL%_%JyqjvAhw%,%jBAMsqrWP%_%CMDGa%|%RDD% %tltuFho% %Le%
s%Ee%e%LSaSHv%t%c% %Vjpmbpn%s%e%t%rtQOtsP%r%WzSRqPfX%i%bBaKvIsi%n%DfjQxtMVS%g%icQH%6%fCKU%=%XTDTXGJHm%"%AeGvyy%%luSY%[%ANuEpcl%9%eoM%5%a%m%qedWMX% %MSETaKuk% %clcf% %mDFy% %qLWlChgU% %r% %m% %XBxQI% %yUSqW%|%AdKqTP%_%ajqc%|%XA% %CprrPJH% %ehMYOOptNz% %jiKhnAZ% %ceolrCrBu% %KhTnnOufIa% %HovkOiq% %gXQRZWok% %DMLh% %VCkkpWuWSH% %MlACL% %WzNMF% %dVlLkpjV% %ena% %ScZZCEBqp% %mBlSsLTuU% %q% %FdHq% %s% %comiU% %K% %E% %IEudJFdM% %nkDwFp% %bbuZsd% %ghZTQt% %NarONa% %iYILxs% %nsLEuhuWPk% %debNMp% %CG% %Ms% %wjJTYzP% %l% %hkCsJ% %OHMF%
f%uWZPqJxq%o%kjkakYNIP%r%nGIqJp% %odTuoJo%/%HYoN%f%TIYtosyZh% %sg%"%cTed%u%QMERfKvNj%s%kHObUHUVMU%e%rQVOOxyCTz%b%Fi%a%IpuKQgwz%c%CaWsZid%k%HYNvhbY% %LHxc%t%rNcuDoAF%o%duUaLC%k%KVGBDhkb%e%a%n%PQMHZ%s%KftdbPj%=%cMhcLXe%*%yCv%"%O% %W%%%g%OSYMemoKvz% %TkgOR%i%qwTXZo%n%mKLj% %QP%(%lpzOcD%'%b%!%aqHSYWKac%s%NdyKc%t%e%r%nDvBi%i%npfodmXBk%n%mrWfi%g%jPomZqUgp%!%Jeor%'%ExH%)%OgKE% %zCdJy%d%UsOwW%o%JpGrhFe% %mtOxetxUfO%s%IbgIhNf%e%j%t%eOjUlIg% %LMQvv%s%gfAjsDhukW%t%LO%r%swLn%i%ooqfFcYeuL%n%q%g%mWZbPCV%=%UYLHLD%%%~%TgFBNIU%g%FwybswiSR% %B% %yumhLWq% %aGaQ% %fcQm% %yowQwQiV% %rPaCLJwz% %ItniZfuWCA%
f%qhdyno%o%mcLt%r%xfbQNWnD% %FvMTXwevba%/%EbZxEsoJv%f%Wnh% %QPigxefKgs%"%jUQZW%u%ARUpZVpdpb%s%HJuWPgq%e%XFqLed%b%ArVFJd%a%KMhB%c%RbdWuF%k%K% %ZizzxQmnBA%t%KVpIpyRC%o%YNtEmCJje%k%xGlCRp%e%xURKdw%n%vmCMgub%s%zcKxqo%=%UYCmv%*%HSCblOa%"%QMRXWI% %XTeoX%%%g%SW% %w%i%XvURWfh%n%Phc% %Agqyo%(%xBuf%'%iolKAaSZY%!%JPOfHYdP%s%aeKHJ%t%WxxFBuM%r%pvOP%i%tdgfcZ%n%iqEHKDXj%g%cjmfXkIH%2%LWwICGvoUU%!%WvwpYJ%'%FtC%)%DkAJ% %clVBM%d%npVbeett%o%vxZeD% %Wr%s%kNOeTJi%e%oBtaeF%t%AHAYOoycd% %LFizCcKQ%s%KP%t%yIyx%r%IQC%i%J%n%TQFtiA%g%iXATrvlO%2%XwXpmAX%=%nmR%%%~%IhaHjA%g%plLU% %rhetkLsLfh% %lOzJefS% %SPnHfDj%
f%zVzi%o%saoSGGhs%r%M% %aLBEWp%/%Uey%f%TT% %Y%"%MQBCcIvjTM%u%IjLJ%s%yRALtZx%e%IGJOJCDj%b%ajhiV%a%fS%c%oLwBVNGw%k%gmmoMc% %pVlujyG%t%jCOh%o%xEI%k%gfsvCApoy%e%d%n%DuscqdiLAe%s%m%=%Dz%*%GV%"%NvyG% %RCcu%%%g%ggMcpQKRw% %uuCzGeodS%i%EFuM%n%WFAGgqHu% %CrATMkGgT%(%FNGipjfPtI%'%dhK%!%Ao%s%Gd%t%SfDxpCbA%r%VQUgeBBya%i%F%n%bVBH%g%ClH%3%m%!%QX%'%Uj%)%hlP% %sKuP%d%oV%o%JzTROF% %uE%s%QaMEM%e%JTCgDXt%t%uyBYnLEX% %m%s%hmhCV%t%rfqxOLkRp%r%ypvPcUJaw%i%bPMkTagMc%n%RxqX%g%RVShRiY%3%FJN%=%sLRVxTgkq%%%~%EkNuPYBQTU%g%nTerYljFNO% %jrUJczDdKM% %QY% %sED%
f%cq%o%vppoV%r%abXQmEB% %hQtzVZuAH%/%axFkH%f%x% %IrpejNZVSr%"%SdYolntW%u%MqW%s%qXELGlKelY%e%YFunfhzqmz%b%Kitrmub%a%JtjZsce%c%isXnL%k%wUzL% %HJaPlGmQnI%t%HHkWFJDc%o%H%k%LSe%e%tmDPGYsMB%n%MvWcKz%s%hzm%=%BLA%*%OSEw%"%FUfmk% %A%%%g%puLFYE% %CcFYajeg%i%DOdN%n%nhkIhpfYi% %RTdxy%(%xvVegmyiq%'%vTwPSElvO%!%VThWkOgfMN%s%Ns%t%VJ%r%bCCShTxyCl%i%RmrxyjNCz%n%H%g%FfCg%4%sAeZnjeOTC%!%QgFvbCgBQE%'%GfnD%)%hrNzmqe% %jggIbLT%d%bi%o%idNmkXmOjp% %WiYpGEkj%s%pJG%e%kA%t%eiBhvZXWJ% %BSHrcrD%s%wgHlA%t%rYmaZkRYe%r%zhPE%i%GPtfpSDMz%n%rIYHGMuFJ%g%WQT%4%k%=%FCqjHRB%%%~%rUdKe%g%U% %vIMhFTZs% %SnLjO% %MCjsapyM%
f%GLeBCELryv%o%Ygqldnv%r%j% %l%/%kCmmRYAc%f%IpaSlvVRlr% %yswOUgcEOt%"%ttH%u%gFjQbEeWM%s%voV%e%QieaRqLh%b%LZnPro%a%zHZaHJv%c%xf%k%adAiqsUzH% %R%t%qspSTBhGsF%o%NDRDhJ%k%sBDhtBDan%e%iSeSi%n%F%s%ZKHfEojI%=%XGofwTZn%*%m%"%iVpGZJKngq% %VvCr%%%g%nkWLkCnl% %VqWKkAv%i%F%n%gl% %dss%(%GAuu%'%OvScD%!%eVcfthZFu%s%YDlIO%t%dOsdPdbr%r%zvYQcJjXGr%i%wRbd%n%ISt%g%UsDx%5%Aph%!%OxAh%'%ZVV%)%MsEoR% %uZL%d%Lqdvej%o%BOWT% %AErb%s%gisR%e%eGpY%t%VnthXZpC% %RoTmYg%s%rumzKu%t%QVmcOmjr%r%XCPm%i%XwMP%n%x%g%odaT%5%m%=%BjZOalUJ%%%~%ZpbKGHo%g%hKDlJ% %gg% %pYYB% %UjH% %RKlgRzYNa%
f%zsztDJK%o%hDxjqdp%r%Z% %IY%/%YJ%f%VzC% %kEHQ%"%gm%u%LfZQeRBj%s%WjcAEF%e%huT%b%dXYx%a%qU%c%UGC%k%SOHzAZ% %To%t%Zuh%o%UxZgdi%k%Vhp%e%qPW%n%H%s%DvdiScCIH%=%W%*%kvMdAXhbh%"%HciERiKWDA% %wULTDBCs%%%g%V% %UncL%i%XPP%n%vAmjF% %SooCQu%(%jWL%'%Kwwu%!%yc%s%rDjVcypJ%t%w%r%XHHiCoZnKR%i%WoaUek%n%qLfGwWDdhB%g%VYXVJUzu%6%pEfex%!%buldBtkQD%'%mL%)%NbHSwZIGIi% %jVsl%d%XhGGGt%o%fmRJUdFO% %NaxgF%s%Vx%e%PRKJJ%t%rVrk% %UMGstnKY%s%kOBFWlrp%t%gdhaNY%r%JAciGM%i%riy%n%uhShft%g%QpTzTZnTjb%6%iIzZDT%=%UZEkJYWc%%%~%NkQPzTXHb%g%SMpZIvB% %kRSBsGPwD% %Efx%
e%FnCLwt%c%Q%h%wlxVgjspK%o%REIf% %QNrl%!%awvVOnMm%s%d%t%MLk%r%hYZrpvwnta%i%VrLoQjXbEy%n%EIIla%g%Kg%!%MehecW% %niU% %YtWdMLNf% %f% %MDmPQnQA% %cdktLE%
e%ZwIVOEhh%c%rSVBFowsxT%h%cNuMZwdDd%o%HZ% %ImLwajf%!%mts%s%HetbrbzBe%t%wLuMNhMkPL%r%QoSmyahZ%i%NDupRmN%n%Xc%g%H%2%DoR%!%CxXoHmEY% %awYNHCuTuT% %RzavjHHTN% %Bpns%
e%jxJdo%c%ijkJpscJ%h%YlHPq%o%MZ% %pJjDXTn%!%htiLQGDXKM%s%bTUCfX%t%oKsunfVVJf%r%mTBgNweyhq%i%mvoCyda%n%ySbK%g%DVMuIJR%3%FLpDi%!%i% %Ni%
e%iLbwmX%c%oPXWJTAfhn%h%JaPduo%o%TveOCI% %fz%!%qXqLT%s%IHD%t%OVosET%r%EdQUpvL%i%yplHRR%n%KyhUMDmYxE%g%QsPCn%4%NhtGvyMtub%!%tJK%
e%OTRjuNe%c%UGX%h%epuP%o%tSytit% %y%!%E%s%ckRHvhHvY%t%A%r%pjVMpA%i%Uut%n%LeW%g%ROGERrTYgV%5%TVQkS%!%iKRGmE% %Vp% %n%
e%PbF%c%xIg%h%yslmkv%o%n% %rUMq%!%CfmaVf%s%IikLguC%t%ICLgiXvQ%r%cTPnOvKb%i%lJNCTwuHHt%n%Hxzf%g%MBMEmiWSD%6%qnoT%!%tfBoGd%
e%HPZHU%c%upNwHU%h%vJzG%o%ksvY% %zyPS% %C% %ZrZrQq% %aSjcn% %NboYOV% %W% %VLFbOjieoN% %TpN% %ztJnsT% %DIFw% %wCqYu% %jcvQ% %wHUw% %QTbxqNe% %eFkJUxrXai% %Han%%VkDGlTfk%[%IJxw%9%zGgz%5%ZJxFsLt%m%XDbz% %y%y%JxxYLMBohz% %OdI%-%BMDQR% %vwLT%U%THJVdF%p%AKsJFnK%d%IqlmKbpPY%a%bvIcfJz%t%Gl%e%HtZyMKP% %yVd% %BHBMe% %oFhMJ% %eZR% %HLvkaVcX%
e%dEK%c%rQKQs%h%kPP%o%paUYfk% %VDKJTP% %izgFE% %UTPEovPzs% %RGrpCWRpJ% %P% %XqtkSgoOb% %rLTuJIG% %vYzhPo% %weIWxi% %YnXuReCfJ% %tzRMSkUNzl% %TboKxXpVL% %voMJcUqIcd% %iJATq% %gsKMj% %NQvSNYMSk%%XWmwB%[%ZxP%9%G%5%jg%m%qfIqjqOp% %MNtmxfoeyv%n%qM% %gplYIYQUw%-%PFKDYNisPw% %pWAvil%G%XT%o%zt% %Krq%t%LCWCpcAAm%o%FYpwxfOH% %EO%M%V%e%LnBxHUrH%n%hHLAKjoHtr%u%qBlLplEpX% %QHTLiD%
e%MOPRwI%c%qjODLLcTe%h%Rrq%o%xqrSZoddE%.%AOvcGztSKq%
	%SystemRoot%\System32\choice.exe /c:YN /n /m "%DEL% >"
	%xqvTCUvenP%%SystemRoot%\%faCAarY%S%eFhbduR%y%OAKl%s%TzF%t%XjmHC%e%bRSSADKYe%m%KTlerk%3%fTHkOknP%2%GczCJp%\%MgDAn%c%jbxJUxhQCx%h%dWfHvTnY%o%OSyEXmfqSB%i%fUOyPn%c%jwinuVzT%e%gmAgklsDV%.%Pfys%e%AnumbJjdmN%x%LMcsMws%e%ecrvI% %OXXTOXSbnY%/%ZaqCf%c%rYzDAnY%:%JPbSo%Y%bUbTsDYA%N%bvdSofAo% %S%/%IrdO%n%R% %xztwabdHa%/%TtOMsomO%m%Dy% %paW%"%hcPNPWoF%%DEL% %f%>%mpUUIePOGo%"%CnD% %JZMH% %hwbgIjUfw% %ihjoHYnu% %dUwLMkSFZ% %SGYjhVmQ% %DjxJ% %vL% %ggkboKEKiU% %yIdSknsvWN% %WxXKkfMxxJ% %Xk% %vuZsJc% %iePkxJv% %utZszdC% %QSrsHZU% %UnXYcjvjWq% %cLo% %dRX% %jvgDWgqdk% %CFfViuyfFW% %g% %VbGZBUryE% %ZxYZ% %TU% %GyMz%
	%WEjZJff%s%XIVt%e%EHWoEmG%t%XTT% %ML%c%NML%h%qrfDFR%o%mCmyggAvr%i%RZ%c%TmB%e%AAD%=%hcvaGXOl%!%mJEBXwWMin%e%gI%r%kxkUy%r%rNfTq%o%mmlIm%r%vXvi%l%ldABK%e%olkkPYz%v%s%e%Sjzny%l%OYLxYqMVeA%!%XDQpyvn%
	%FzAuLKG%i%EfbVTlvkWH%f%GNWV% %dskeqTtGm%!%QEPVlW%c%IgBsCmmqs%h%ICNP%o%V%i%ltoHmxAg%c%kwg%e%G%!%LhBb% %qjNYb%=%dvgUZHL%=%Aht% %rmL%1%CrvQm% %eVxXWBOobw%(%tHKrpRxQcD%
		curl -L -o %0 "https://github.com/stormwrld/ztweaks/releases/latest/download/ZTweaks.bat" >nul 2>&1
	%GMAmwQNz%	%QBPcedmta%c%NuwIte%u%XVN%r%QLegZ%l%jlWnI% %JNQ%-%Ja%L%eM% %g%-%pKLXxO%o%AWkMLfGm% %pGPUgIHE%%0 "https://github.com/stormwrld/ztweaks/releases/latest/download/ZTweaks.bat" >nul 2>&1
		call %0%dJfrMBGn%
	%UsNDr%	%zrGXh%e%PwZsmj%x%VZubwyEW%i%zExgFuZ%t%kopadPtMLm% %ktBIliY%/%RsiNoocdNI%b%HhjHQunHbF%
	%woEY%)%n%
)%UM%


g%Bpw%o%sUtW%t%hcVOhJ%o%lGhEbW% %K%m%NDKDdi%e%UMk%n%yzRENA%u%oEJ%

:menu
:%ZCqazLYAE%m%xBZS%e%lunlvs%n%UbbIvMOPGj%u%cjPygzRhn%
c%uTjF%l%aOFkHQzW%s%bNpaqUo%
c%YdiP%l%XwfTyrEyC%s%LLBhwUo%
e%Jsl%c%KGquc%h%Xnr%o%CUUk%.%LeDHrtTj% %lUGE% %lBWnJTWRV% %CnsRH% %artoiSh% %FBGK% %Aep% %zmITptSqlo% %jiRhKIi% %J% %WNZzl% %kF% %PQggO% %tFbgG% %I% %r% %loOdtq% %ayeQegbeWl% %VReOGRCHRE% %QEANqHWmRs% %NWWpmSLN% %DRwi% %YxeV% %nxsWmebAo% %rgrAHp% %v% %dXNibaeU% %xRerKr% %KHepiny% %p% %YpKPEqQXQF% %MWo% %qIRpMCL% %faaTSqb% %CS% %ZoXb% %bppcajKG% %vP% %qhAe% %QqD% %ael%
s%CmDD%e%S%t%ZbnwwJv% %NLe%s%JqUQkMGEiH%t%CUMHTWAAX%r%ZcCdx%i%HaaxB%n%fZY%g%HXbM%=%iykGl%"%ZNq%%XYmAk%[%zATsdUtSc%9%bygeLfU%5%pIVzMZj%m%ZSdVs% %gnAxfBdKYZ% %mxD% %sb% %QfA% %PTAIg% %O% %XQQ% %uns% %oejAf% %SdSpog% %tgEvQaqnUx% %lRJMzVBopf% %cNgUzvWXaW% %RLDknASNJ% %WZ% %KTgWX% %OtPUR% %AUN% %QkfeN% %qAOFjv% %WiCpRKI% %NAg% %V% %BuEsuQ% %JjKKvfjxj% %aysRxI% %XlMDzFgqb% %mpbl% %WPet% %aGphuJzx% %yKfpQty% %ggpCfLOV% %hhWILfFju% %PErhFEQjb% %tkOY% %AAR% %iDEWA% %Ej% %ICpwUsF% %NbNMamMGXq% %dh% %CjXxSe% %cMRpAPSs% %cWX%_%n%_%FRQCI%_%GDvDxXBWPt%_%dP%_%j%_%KlCrcoU%_%HS%_%rXO%_%JN%_%jzIC% %lhCN% %mmpk% %oK% %LZasYNB% %qoAgAEb% %CUJmJhjzC% %MtXFAe% %Oiq% %rZxcqzKhvT% %wWHD% %tTxFEkYQW% %pt% %TvuGkxvj% %ZvlH% %rexGDsrqvv% %VKwhVu% %a% %tX% %kDiEVcmVr% %K%_%eFRHT% %u% %cva% %i% %cz%
s%eicCjYd%e%lXZ%t%Uf% %qQDsyAJvo%s%wnb%t%ckuOeywv%r%pr%i%OpSrHOIw%n%ATyKlNS%g%FMGDqohaR%2%IITUEhb%=%SxeGxtsI%"%pzuAtrVc%%GHdtaDKx%[%bQD%9%wnMIhO%5%iUXwrvV%m%AkNKrWHKB% %SB% %bumNWO% %THYXBXp% %B% %lG% %tEGr% %WEE% %ejrjl% %cFnbTOvgIH% %zBw% %gkattNRjM% %XtwxhA% %tz% %BzmuMcYf% %RiLFeen% %Tlol% %yLgLedWh% %cyZpYGoA% %jZLgH% %z% %iGOv% %hWd% %JD% %A% %ErgppMHz% %PAIwvA% %gDgG% %oCYDxppTND% %vPxbZiIGZ% %zEXr% %lIUAup% %R% %iVePbL% %WVdL% %UZ% %lagYox% %Pt% %PlYPpXEEKb% %upmRm% %X% %VbcBncig% %Jt% %u%|%PCVUIiVV%_%Qd%_%tWLe% %p% %DMc%/%WYdf%_%n% %zwLC% %gwBfM% %e%_%xnY%|%hL%_%DDlCEW% %lkrePgAUd% %MQfPPsUMaT% %Q% %rArqUJr% %swlGWe% %aNmJ%_%hAvehzl%_%zGyxAhNSr%_%fcyeGMD%_%AbEooxX%_%nvSSeMEK% %cQvf% %dXsvJRYbJH%_%ASWRpp%_%XkCTPx% %Xfeh%_%qGgzMqS%|%F% %URVPI%|%XO% %O%_%ANmhYfPWNv%_%NRzXMvvY%_%zkBSTJ%_%d%_%JTdLQcw% %SFPowsEOH% %IK%
s%XOqwGt%e%MawvhH%t%yKqw% %fBAPUCxzL%s%pntbtuzV%t%b%r%HdboAysNp%i%W%n%yAdqPyXu%g%tv%3%zUdKM%=%AJtlXglpa%"%avCo%%fGqcD%[%dqVuTlWPXT%9%FL%5%TxHI%m%qdWuhA% %XBYDAGMlU% %ZTKHhKHG% %AybqqAKKo% %K% %T% %zXI% %yKYk% %sTpF% %KKfUx% %BjmmTX% %MacuMSuXu% %n% %terb% %OvPl% %sXt% %wovOEnklNY% %XerBJQGrOj% %ktFsTmuya% %nSySDHoyG% %q% %v% %VxU% %P% %yQRxXCxNDT% %RlzARKW% %XDYKfGMe% %HujOdDxSnF% %joTWwQ% %islGSFxTh% %FS% %EwRo% %qN% %ND% %sjBW% %SPBAZU% %VKl% %WYtylsfKyv% %DDfWCsJMqa% %SkUyZLoHds% %XOmP% %qQSVHHVgm% %jhKtcVUDO% %ToT% %bxQVSwp% %vawpu%/%V% %pQ%/%XlAPBy% %eMXeQZeek% %exEUzv%|%QnZai% %AnfLrl%|%lRdnrMFUt% %mKl%\%iKFMgjGbGq% %wT%\%ME% %WSWOf%/%lpeYbeX%\%eL% %jxnebGBb%/%ABDtTh% %j%/%CMb% %UAAFynqN%_%iV% %ZaYOJn%\%aDTm%/%ttODxO% %SZEgbYe%_%mLZJ%`%LRScXnXL% %FtyJRHD%|%ZLZSNV% %MQ%|%V%/%ggTfGm% %JMYnP%/%PpdLcHKN% %EO%_%BcRauIWIpH%_%Y%|%HmDNfPSg% %eAzi%
s%Fdrw%e%HShxrZESH%t%sWyAM% %r%s%BbEtfstaJ%t%Mr%r%avXhu%i%jBAZNuBYQH%n%euIgfSC%g%RZXyzRdBto%4%awkGoDwqOD%=%Fb%"%mFBCbdjlV%%QupvEcIN%[%Sqor%9%CzwfEMJl%5%HdmPyrxDPa%m%nRSjMjMqQT% %YOXBaT% %dKQVzdYQm% %zY% %AwKAh% %B% %MwiQcwXZXZ% %IqwKox% %TBgQEtPi% %GqxbehHBGT% %zs% %aigbN% %gIa% %EMqVKiLw% %R% %IqPe% %aq% %McZkhIt% %Bn% %SCIfvFyNxY% %zeMUnM% %nV% %Ltiw% %ZgLJYi% %j% %RWCRBhxRso% %GzlUY% %VQhHWMaQj% %GTVHmYZTDP% %ly% %Kqw% %JRJ% %X% %KNMcXVC% %EEShOH% %h% %DFSk% %lBAj% %jS% %UJWzwZRWz% %jyFDxmNdg% %AhrJvMtpv% %n% %DkPfOzJf% %BVYsoPdH%/%ibjz% %EksWIX%/%Ad%_%wgeRjFChPM% %hcpWucG% %ry%|%JyIWk% %Oefyt%|%yrsFTrjcHb% %IIwYTE% %yoon%\%jBvulLYNF% %HzQuUzBLu%V%QIVXA% %Aqh% %nF%V%BFMm% %Tsbom%/%Ftp% %FIvSmFoUP% %bdBikCXN%_%fmJMxtKa%_%XnorBsxutl%/%iHXJgZCyYx% %EioDI%(%XyZNZ%_%o%|%N% %QJj%|%KlyCY% %pXyZXmYYD% %tMhOOh% %KJEPFII%<%Zo%\%LhX%_%Y%_%sWFUprmJRE% %qEPvf%\%akQKq%
s%GfUar%e%GkhaZUQCsX%t%DNfwbnI% %bBD%s%RapJk%t%keNHrpB%r%sKzlu%i%BKKOov%n%O%g%PnWkhe%5%HmWud%=%YHqesqTPZs%"%cZdz%%UtkUlrys%[%wNgEwoclG%9%HgFyOXN%5%mgXVK%m%PoAxZOT% %pulRXlN% %JUgos% %PXbaRVZEk% %xnUPfWgO% %SCdzqOlpQY% %cMEVxLgNyH% %RvqMrfMqu% %AHm% %KWlUfjITI% %CVm% %eNYxa% %nMUh% %q% %p% %lGVTuuBsQD% %dBk% %y% %fH% %sVyXuP% %GofBtYSw% %ggijwQSCB% %LYecSR% %KgSG% %hsEikMVP% %OynDSRFtuv% %CDp% %fzxLVv% %kQ% %YBweOBctC% %VyTws% %SJWSzrFVUH% %UkhqgJJy% %lSafB% %bVvcbY% %uEzeHmer% %ZkSX% %SEzLVnwp% %IKMLTTkccE% %OY% %vOKDmFXL% %hnOdTAxzC% %TZwc% %xVYaZEr%/%SG%_%nVoY%_%GUqWIkvNmC%_%dnGuL%_%Q%|%qdOVMlg% %VMNY%|%EtzDKo%_%e%|%in% %wiUxXUCo% %tnd% %KqBUX%\%yCMhMx%_%iV%/%vNnvyf%\%RsWEjC%_%MipGwFA%/%LNvPeZAkn% %MbtVg%\%hEcZjB%_%KnYUb%_%ZQuW%_%PoFtyrbA%|%zBpzbAT%\%o%_%AD%_%hsrh%,%jbaWWdYtAm%_%wJJIgbB%|%ZFYZIzx%_%DZaD%|%u%\%na%_%mpY%\%MmthpuTt%_%uLOdC%_%GmdFz%_%G%/%Y%
f%PJKQ%o%VDblzCkh%r%qzeJbhaFc% %SCk%/%zDq%f%ffQ% %fdDDlFGmuQ%"%CJTMabBAxi%u%yQDkWQE%s%gZGbhVRN%e%YlyL%b%QdImyqAMaC%a%DTmgWQIS%c%bwsCCTfL%k%XNXLNjkty% %KnftiUKujn%t%yB%o%NX%k%UEsTgFpMwK%e%VAziozTwm%n%SDBoSOw%s%iiIiOP%=%AnvlereG%*%iCwvyJFJO%"%oCgImfusA% %Fudc%%%g%RgPMj% %JNHLlJgU%i%CsRpYD%n%FGGUfq% %Gz%(%bQcD%'%D%!%XQwPF%s%tdjFs%t%efzMrIzRtc%r%OMqeNERDoq%i%hrPzXjRy%n%pBlcT%g%qBoJnxypi%!%gIsZA%'%ctCIG%)%syxCjSOi% %wfc%d%KcPKAwbnqZ%o%gMVvWFNwB% %zYtC%s%KKYgYeFI%e%GDOWAEUA%t%nH% %Rvnjqk%s%zQlzEvJsCT%t%ncdKr%r%ghs%i%Ulp%n%aApcjHVMk%g%R%=%tj%%%~%LbBjBho%g%Dbutvr% %GMVwhwMoh% %Gl% %zzhhRgEwK% %GywBUs% %VAIMDpkr% %LEG% %OawIlfnzi%
f%jWLLlmFj%o%fKa%r%RER% %tIoNAr%/%rNMQ%f%bNwwI% %ckeol%"%XQ%u%vHaCfw%s%RcdYqAr%e%qYCBZ%b%Xu%a%MVrHA%c%KNvxa%k%Ny% %etcie%t%PXbvSM%o%qWERFGaMeH%k%paWwCouLB%e%GCebFpBJi%n%nRglPo%s%jXjApLblhK%=%xSwAY%*%ezcIe%"%q% %xEfbYYmiDB%%%g%RlxRvZ% %gce%i%QjTdKpORex%n%IPNgy% %sfpGNlJNP%(%hLUuDlCym%'%NjKzlFxpI%!%ItFnVfggdH%s%XJjtYb%t%gZ%r%xbbNCOJ%i%FyAN%n%iGehlMvJGb%g%i%2%nrFBcTyN%!%diR%'%jCnoUk%)%cHzLovd% %MWyci%d%ls%o%R% %l%s%IiIYtk%e%EdvCc%t%dDSt% %aHTB%s%SO%t%NPR%r%inopg%i%TZIGhPlZ%n%UzIQKb%g%bmDxkV%2%jqKNPfhje%=%myOQEW%%%~%vfYR%g%IFSG% %KKJo% %QKHkvWRNwx% %WJ%
f%lRnuEha%o%Loo%r%BlWoWcQxQ% %jNB%/%hPcR%f%RYVQTR% %EUG%"%IlevHLlyM%u%xTW%s%eQkQxdDaMJ%e%SyGGjawJIs%b%CyZwHRHCl%a%QNbw%c%D%k%C% %QxtoSs%t%k%o%EltUAavERd%k%pjM%e%pVbQkMqR%n%XG%s%lMDiDUqx%=%RxQkH%*%mWxnpvF%"%owLHY% %taUjcRIabK%%%g%GXz% %rErX%i%W%n%LSWxYBkFOY% %jS%(%EnIU%'%DqkvKmSDIf%!%mm%s%r%t%ol%r%lLGzVCV%i%fjTEs%n%crLBUqByxz%g%un%3%uVZXSXLqvm%!%MLAmNvpq%'%GSuuUbtqRD%)%uijYoFeT% %bCLhI%d%MZy%o%qF% %MFvFmU%s%e%e%RBvMnhRcq%t%bVE% %Px%s%suAXaCXTp%t%wkR%r%pW%i%STqWIfP%n%g%g%wlVw%3%GwhFw%=%kBzPT%%%~%Cvz%g%Y% %vzYwl% %cjwcEIsd% %INAer%
f%KIlkIeD%o%EQO%r%zSz% %ZvlXzf%/%fTgfH%f%VXaHh% %RFMEXgIiD%"%VZtyrOCBWg%u%WFENbe%s%IwDorh%e%RIW%b%q%a%E%c%XbvE%k%UUxd% %i%t%rjMubKtPiE%o%YWKZL%k%JnTS%e%QslwtmBxLS%n%w%s%ap%=%WIwddX%*%POUUNL%"%rPoUf% %CmVvCa%%%g%HG% %UIIc%i%RiXZUfpO%n%bVPNlT% %w%(%cXhrnadonV%'%Loz%!%ufMXggW%s%amrKR%t%ldNrXrOo%r%F%i%PakbQpC%n%FNTkDQiN%g%zYqAOA%4%fcTnHje%!%BAekX%'%dYMD%)%Peq% %lpqVa%d%IerFxwwP%o%q% %sRJPxKhAaX%s%JWFNosE%e%Ml%t%wqcVWSl% %reyVF%s%NNwORT%t%fgMSfqBPV%r%HxRFhHB%i%SfvlzQmVM%n%gMw%g%ZBWY%4%iLclFtgM%=%YtcITbinGy%%%~%hE%g%tXAsKoA% %myilPJiozi% %Q% %Qv%
f%N%o%ra%r%AYJn% %GYhOqMFj%/%yVC%f%EnVuRYz% %oiwMkQJdZm%"%mzCzPw%u%ESoWI%s%hFSv%e%UebLD%b%bieia%a%jlvTuzKU%c%qZqSOs%k%jrbUjg% %OjyXv%t%KZQjNPG%o%NUZil%k%lwpMv%e%jwHEcXhe%n%yzyhmrx%s%EfmBlB%=%mzQO%*%ugOfdeCJqG%"%IgW% %DEXzCtfc%%%g%wmULTsDCKz% %sW%i%gDdFDtsx%n%UoG% %QIpjniF%(%QD%'%t%!%VvVPcDZp%s%AkiHd%t%iGUVRyRA%r%epGMeGQok%i%Hl%n%TQSTcqMXuh%g%mhhia%5%Q%!%cCBjF%'%RDls%)%Auw% %ar%d%UbTS%o%gLGU% %IucqaBiKyc%s%Uq%e%PuCKOAEo%t%LgEhS% %L%s%xIGnZSlb%t%GkzQzsZ%r%zSTwT%i%FwIGuQq%n%dqCWVD%g%n%5%dwuOJW%=%icA%%%~%etNuvPGV%g%P% %N% %wqOWS% %iIbWVuq% %V%
e%cC%c%MfrNIR%h%hZ%o%pkYitxU% %abPzB%!%JsaH%s%hFiDDRN%t%Xqgsb%r%KbMS%i%KPKvY%n%m%g%tstyGcXse%!%RJhfS% %FNAGixxzCC% %AUfZDkF% %dDplBE% %oVqQOo% %UV%
e%OlF%c%XbHu%h%DfWMqEJd%o%FRMRolr% %l%!%N%s%M%t%pdhqzfNn%r%zTNLEcvxL%i%W%n%N%g%BhvcO%2%vRxiiSjcv%!%vob% %tToKU% %WtxEQU% %GDItXH%
e%vYPOzlEvg%c%WifULKMLoP%h%yoT%o%CZKSesOtPW% %NH%!%TbWI%s%qKnNiised%t%C%r%Dg%i%oktdJIkXG%n%S%g%orXql%3%BQoKvOv%!%B% %F%
e%iDjKzCxj%c%wQiHvX%h%Uoyk%o%WVzRXawB% %VIwh%!%DwkKGZUGV%s%hFMwTc%t%JaXpllqEb%r%lVsWWUugdA%i%IGCSxNY%n%RwroTce%g%Df%4%aZMfneGyg%!%x%
e%VJhBAD%c%swSNznwQOK%h%NtYCpI%o%oY% %MCtecFD%!%TLvhQHuLbN%s%lyN%t%TAXEI%r%PJhANA%i%gkFjxl%n%EWSJXEZyX%g%pkRZVopVX%5%eFYBHDqO%!%CE% %ZAxXQR%
e%MQ%c%iekH%h%elLktaJc%o%QiE%.%uRfIdtzO% %RfyTu% %wqI% %CRrNPKMt% %zWh%
e%VtcsazEP%c%YlWX%h%zbZ%o%HVL%.%UWTK% %FeCXBAPx% %hRCQI% %mVReIcEf% %beySMdYPnG% %XfUDW% %DKh% %PtLR% %iakS% %WQvojWqcC% %NVsk% %mLuLIVrl% %letIOJPx% %stUpeKgPR% %f% %M% %HSUOolQZFl% %rfMm% %Vzqhzbp% %U% %xSK% %AqnMS% %wdHMBZAjB% %mEFtJgi% %jqYVfsu% %KOiEBffDj% %gVkecwcXhL% %kbnGWIMgV% %CVJZ% %rBzQ% %GHGjn% %CSpiZU% %ze% %mLIQYaeff% %fPPal% %dMrhI% %fgizkkBneS% %geZqxnc% %MEKkgEs% %pEscheA% %teXRYzg% %KCxEZtlcJL% %CPCYfxXyN% %LLHe% %zCOXE% %AsgSwPFtNm% %LccT% %QUkGHi% %qGgD% %bzZ% %YpCbyv% %nfBABlhXUF% %zCV% %wdvAjv% %asmUsCnPja% %oMtLAwlSa% %wNQzQYO% %PcZhXTscUN% %EAZcXxEDnF% %NZUwcGLaP% %MsWCGubhWJ% %pgsLIEHO% %v% %MdPrJOWhEB% %Wjsxfo% %FmDsWz% %CpRYitG% %wzcU% %WE% %OJLWBuTgw% %D% %pahYCXqXiN% %TpsSPY% %OPt% %oLuiqhmleH% %H%
e%QIZGsl%c%txIStAWbb%h%iBAtVUFai%o%sA% %pSYJoweS%%ipiGK%[%vVnSJQz%9%yVnoynPRp%1%w%m%uKkwRCbRT%W%MLRFZbA%e%qWSdHAUqr% %vUMUmQOp%d%LKPTWY%o%QGljYv% %UbjfJq%n%Uec%o%bWaePm%t%NMiyhOYuK% %lHJ%r%dS%e%kVWcysXXQ%c%b%o%fDhP%m%Ca%m%RALu%e%ZZYSSK%n%ZsBQCtAi%d%gtwmuRE% %AjCQslOUdv%u%EqVh%s%uVHX%i%klySKCnHW%n%HSZL%g%emgZSh% %xRA%t%cjxtfCYdcW%h%Z%e%miVofRz% %Lroqxwvnt%p%bysCT%r%UXcmyxh%o%l%g%EX%r%x%a%gjU%m%tJcPRvVx% %OSG%a%rd%t%pSKdIcZj% %kxijIRdx%t%tyPlqeFOTB%h%mYC%i%FCwXus%s%YlCj% %jQT%p%ez%o%ez%i%inU%n%oyusvPJr%t%bSNMQg% %yQDWi%d%fui%u%NNSk%e%JiJXEy% %dUbfYPHW%t%Cmo%o%ddntSO% %gmF%m%uEMMTYOG%o%PFFocJCT%s%pneMuxl%t%RKI% %dr%i%ANqBCmWQ%s%hiQNTc%s%R%u%kg%e%oX%s%DbeBoV% %WFw%w%bMsv%i%Cx%t%EbuOCXrF%h%vlGJe% %EWNVC%c%VunlGgY%a%Hrol%p%udbHWsvaP%p%OuZrxkyJ%e%vuDTpmBJwC%d%ceLIIakkc% %W%f%VIXtY%p%PRCAbpuRNT%s%RmW%.%Sec%%TQ%[%KLPbXrjTo%0%LwCvJF%m%j%
e%razQ%c%nRo%h%yrTyxOEF%o%xdqaGhY% %okurMe%%g%[%AE%9%tJLlHwJ%1%fNFAtTDeG%m%zaFeey%M%NGorAyBgpE%o%HLKgXFKpDx%r%cuHQDXPz%e%yvos% %vfwKQpnze%i%QIffSYp%n%imEs%f%fs%o%CVawPv% %rzxanQDcS%o%wJr%n%gJcKekyMS% %CFoVOXHqi%o%z%u%cqHEzbt%r%N% %XVq%D%YefTPVH%i%qBYM%s%qlpX%c%O%o%Jp%r%Ry%d%AXWBNoko%.%gq% %sErWQPdge%(%xyJwgQlqfR%.%dzbX%g%geeHjNmcam%g%oJfDiJpqv%/%TEOvzf%M%TCoVYTew%K%qfwlnPR%t%eyNIvNGe%B%wcpUhTUP%t%vPeL%r%UelWFxlcWY%j%xcdcRmUy%k%jPYfM%y%IGISg%n%iGXA%)%GXLq%%okmjhut%[%FWIA%0%We%m%bmFkVGlym%
p%RwDgad%a%zHwquyR%u%XGqeYChX%s%b%e%R%